language: node_js
node_js:
- '8'
cache:
  yarn: true
  directories:
  - node_modules
after_success:
- yarn coverage
deploy:
  provider: npm
  email: toxictoxer@gmail.com
  on:
    tags: true
    repo: chinjs/chin-plugin-gulp
    branch: publish
  api_key:
    secure: Ih+j/KjcNMw7gp8mgYN6Cxe4RJXH0Hxz7Uvd3+Bdj3jTUImOocmLfTa4hgeLlaQL/CKr/JqeWMTIFh2SHVUeJFuGDiDAMHCGJCjwWBzazfs2IkeX5vAICSXQ369cX9CxWp0nSJxVjaLluobu+ZPVpzeKa/2nlRXAhqT5XneaBCE0NxknlRnFYWaLCYOnjs8vKSyJv+5Lc8App1CduopayFAkEcT5+SOGRnP+NYnwcn9glj9esjVMr2IUkfn4o/HHEX9TVP9R60cxPjVAHkCJUl8MSFhya3Ffv1EJKLaC3/ipdaazDu7J4KAXZpFIXkxvTU5M+A3ABoxDF5J6RNIm7V2ZCGySAHGLMF5jWa50rCVm3yqQWQdmlpGKfj1yyKXo3UHER/6UlQBaNnZ0wChmGj4AKaaRKLofBbRq2AH2jnO6kiVTcLo3OJ4Ie1h7E4owu+u/SVMk0HOJKjLCPaB3iYES4Q3bBT9ckw+ADumZMEezS4+OT+54QfwBRle3ToyG9Ft/P5rwlBWdFw99n+0A6X1rdLC8WN55joqzCFKWAHggmfeFu24dN1rKQf4nN9zWphdpMls2hPp8IIBWCuEyC8mFv/tWq6Q4ldkDl0E8wR/gQxHRW7EqDRt49uPPzrpfEWP63Spx2zD/g1OKz2SPvCdxsSXEd8jH409+DvGmliw=
